package com.blogspot.kotlinstudy.lognote

class StringsEn private constructor() {
    companion object {
        val STRINGS = listOf(
            "File"
            , "Open"
            , "Open Recents"
            , "Close"
            , "Exit"
            , "Setting"
            , "Adb"
            , "Font"
            , "Log"
            , "Start"
            , "Stop"
            , "Pause"
            , "Clear"
            , "Rotation"
            , "First"
            , "Last"
            , "Bold"
            , "Hide"
            , "Tag"
            , "PID"
            , "TID"
            , "Filter"
            , "Windowed Mode"
            , "View"
            , "Full Logs"
            , "Help"
            , "About"
            , "Bookmarks"
            , "Full"
            , "Incremental"
            , "Highlight"
            , "LogLevel"
            , "Scrollback"
            , "Clear/Save"
            , "Log file"
            , "Connect"
            , "Refresh"
            , "Disconnect"
            , "Apply"
            , "Scrollback(lines)"
            , "Split File"
            , "Color"
            , "Filters"
            , "Keep"
            , "OK"
            , "Cancel"
            , "New"
            , "Copy"
            , "Edit"
            , "Delete"
            , "Save"
            , "Select"
            , "Adb path"
            , "Log path"
            , "Size"
            , "Connected"
            , "Not connected"
            , "Append"
            , "Select file open mode"
            , "Open files"
            , "Append files"
            , "None"
            , "Add filter"
            , "Add cmd"
            , "Cmds"
            , "Retry"
//            , ""
        )
    }
}