package com.blogspot.kotlinstudy.lognote

class StringsKo private constructor() {
    companion object {
        val STRINGS = listOf(
            "파일"
            , "열기"
            , "Open Recents"
            , "닫기"
            , "종료"
            , "설정"
            , "Adb"
            , "폰트"
            , "로그"
            , "시작"
            , "멈춤"
            , "일시멈춤"
            , "지우기"
            , "회전"
            , "처음"
            , "끝"
            , "Bold"
            , "숨기기"
            , "태그"
            , "PID"
            , "TID"
            , "필터"
            , "Windowed Mode"
            , "보기"
            , "전체 로그"
            , "도움말"
            , "About"
            , "Bookmarks"
            , "Full"
            , "증분"
            , "Highlight"
            , "LogLevel"
            , "Scrollback"
            , "Clear/Save"
            , "로그 파일"
            , "Connect"
            , "Refresh"
            , "Disconnect"
            , "Apply"
            , "Scrollback(lines)"
            , "Split File"
            , "Color"
            , "Filter list"
        )
    }
}